#!/bin/sh

# global settings
yabai -m config focus_follows_mouse          false
yabai -m config mouse_drop_action	     stack
yabai -m config mouse_follows_focus          off # only supports "on" or "off"
yabai -m config mouse_modifier		     alt
yabai -m config mouse_action1		     resize # note that move does not work without SIP
yabai -m config window_topmost		     true # floating windows always on top
yabai -m config mouse_drop_actions	     swap # swap/stack when one window dragged on top of another
yabai -m config insert_feedback_color	     0x00665c54 # for 0x00, the last 2 0s set the color to be completely transparent

# general space settings
yabai -m config layout                       bsp

# focus window under mouse when window destroyed to prevent no window being focused
yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"

# window rules
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Photo Booth$" manage=off
yabai -m rule --add app="^Loopback$" manage=off
yabai -m rule --add app="^Stickies$" manage=off
yabai -m rule --add app="^Contexts$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Alfred Preferences$" manage=off
yabai -m rule --add app="^Syncplay" manage=off
yabai -m rule --add app="^Copying files$" manage=off
yabai -m rule --add app="^Terminal$" manage=off
yabai -m rule --add title="^cloudshell-testing$" manage=off
yabai -m rule --add title="^Parallells Desktop$" manage=off
yabai -m rule --add title="^LICEcap" manage=off
yabai -m rule --add title="^Digital Color Meter$" manage=off
yabai -m rule --add app="^Just Press Record$" manage=off
yabai -m rule --add app="^Kap$" manage=off
yabai -m rule --add title="^OBS" manage=off
yabai -m rule --add app="choose" manage=off
yabai -m rule --add app="^new-note$" manage=off
yabai -m rule --add app="^notes-search$" manage=off

echo "yabai configuration loaded.."
